name: requran
version: 1.0.0+1
publish_to: none
description: Aplikasi Al-Qur'an.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: 0.13.5
  google_fonts: 4.0.3
  lottie: 2.3.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
    - assets/image/
  uses-material-design: true

